added options parameter to linttest

diff --git a/linttest b/linttest
--- a/linttest
+++ b/linttest
@@ -1,6 +1,8 @@
 #!/bin/bash
 #very similar to jslint script, but this exits with error code if lint found
 # this is useful for using in Makefiles
+OPTIONS=$JSLINT_HOME/default_options.js
+
 if [ -z $1 ];then
 	echo "No source directory given"
 	exit 1
@@ -9,12 +11,24 @@ if [ ! -d $1 ];then
 	echo "Could not find directory: $1"
 	exit 1
 fi
+
+#second parameter is (optional) jslint options (filepath of file with options in comment)
+#otherwise default options file is used (in same dir)
+if [ ! -z $2 ];then
+
+if [ ! -f $2 ];then
+	echo "could not find options file: $2"
+	exit 1
+fi
+OPTIONS=$2
+fi
+
 #right, now lets lint all the files 
 for file in $(find $1 -name '*.js');do
 	if [ $(jslint $file | grep -c Lint ) -gt 0 ];then
 		echo "found lint in file: $file"
 		#show lint report for this file
-		jslint $file
+		jslint $file $OPTIONS
 		exit 1
 	fi
 done
